# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_chofer', models.CharField(max_length=50)),
                ('descripcion_chofer', models.CharField(max_length=100)),
                ('rut_chofer', models.CharField(max_length=10)),
                ('fono_chofer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('descripcion_equipo', models.CharField(max_length=100)),
                ('patente_equipo', models.CharField(max_length=10)),
                ('serie_equipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('descripcion_modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=50)),
                ('descripcion_obra', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='Modelo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CialSistema.Modelo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CialSistema.Chofer'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CialSistema.Obra'),
        ),
    ]
