# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_diaria', models.IntegerField()),
                ('operacion_real', models.IntegerField()),
                ('relentis', models.IntegerField()),
                ('consumo_combustible', models.IntegerField()),
                ('rendimiento_promedio', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='horometro',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='operacion',
            field=models.ManyToManyField(to='CialSistema.Operacion'),
        ),
    ]
