# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0006_auto_20170214_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='consumo_combustible',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='hora_diaria',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='operacion_real',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='relentis',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='rendimiento_promedio',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20),
        ),
    ]
