# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:55
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0007_auto_20170214_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.DateField()),
                ('longitud', models.IntegerField()),
                ('latiutud', models.IntegerField()),
                ('evento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='operacion',
            name='consumo_combustible',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='hora_diaria',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='operacion_real',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='relentis',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='rendimiento_promedio',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20),
        ),
    ]
