# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0008_auto_20170222_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='latiutud',
            new_name='latitud',
        ),
    ]
