# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0010_auto_20170222_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='hora',
            field=models.CharField(max_length=50),
        ),
    ]
