# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0014_auto_20170222_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
