# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:28
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0017_operacion_maq_dia_operacion_maq_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='hora',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20),
        ),
    ]
