# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0018_auto_20170224_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='consumo_combustible',
            field=models.CharField(max_length=50),
        ),
    ]
