# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CialSistema', '0019_auto_20170303_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='rendimiento',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20),
        ),
    ]
